pipeline:
  build:
    image: maven
    commands:
      - mvn assembly:assembly     

    image: java	  
    commands:	  
      - java -jar target/calc-1.0-SNAPSHOT-jar-with-dependencies.jar &	 
    

